-- 1. Create the bookings table (Drops existing if there's a schema mismatch)
DROP TABLE IF EXISTS bookings CASCADE;

CREATE TABLE bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id BIGINT REFERENCES properties(id) ON DELETE CASCADE,
  guest_name TEXT NOT NULL,
  guest_email TEXT NOT NULL,
  check_in DATE NOT NULL,
  check_out DATE NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'cancelled')),
  total_price NUMERIC NOT NULL,
  adults INTEGER DEFAULT 2,
  children INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Add some seed data for testing
INSERT INTO bookings (property_id, guest_name, guest_email, check_in, check_out, status, total_price, adults, children)
VALUES 
(1, 'Mohammed Al Fayed', 'mohammed@example.com', '2026-10-12', '2026-10-18', 'confirmed', 4200, 4, 0),
(2, 'Sarah Jenkins', 'sarah@example.com', '2026-10-20', '2026-10-25', 'pending', 1850, 2, 0),
(3, 'Ahmed Hassan', 'ahmed@example.com', '2026-11-01', '2026-11-10', 'confirmed', 12500, 6, 2);
